import type {Metadata} from "next";
import "./style.css";
import { Inter } from 'next/font/google';
import { Sidebar } from "@/src/components/Sidebar";
import { ThemeProvider } from "@/src/context/ThemeContext";

const inter = Inter({
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <ThemeProvider>
            <html lang="en">
                <body className={`${inter.className} antialiased h-screen w-screen flex bg-background dark:bg-neutral-900 transition-colors`}>
                    <Sidebar />

                    <main className="bg-slate-200 dark:bg-neutral-800 border border-slate-950/10 dark:border-slate-50/10 rounded-xl w-full p-2 md:p-3 md:my-4 my-2 md:mr-4 mr-2 overflow-y-scroll overflow-x-hidden">
                        {children}
                    </main>
                </body>
            </html>
        </ThemeProvider>
    );
}
